version: 0.0
os: windows
files:
  - source: \
    destination: C:\Custom\Fekra.Pika.Ocpp.16.CentralSystem
hooks:
  BeforeInstall:
  - location: \before-install.ps1
    timeout: 900
  AfterInstall:
  - location: \after-install.ps1
    timeout: 900